### ISSUE TITLE
기능 추가 관련 의견 올립니다.

### ISSUE THREAD

**Issue by conggooksi** [c9u11/koen#70]
코엔 잘 쓰고 있습니다.
쓰다 보니 있으면 좋지 않을까 하는 기능이 있어 이슈 남깁니다.
입력하는 와중에 단축키를 쓰면 커서 앞에 글짜가 싹 전환되고 한영까지 전환되서 계속 입력할 수 있는 기능을 넣으면 어떨까요?

**Comment by c9u11** [comment]
2.0.0 버전 사용바랍니다.
